blank_issues_enabled: false
contact_links:
  - name: Question / Help
    url: https://github.com/Imperial-Laboratories/empires-and-fortresses-1.20.1/discussions
    about: Ask a question or get help in Discussions
  - name: Fabric Documentation
    url: https://fabricmc.net/develop/
    about: Official Fabric modding documentation
